### PR TITLE
Bump version 1.0.3

### PR DESCRIPTION
**Pull request by ugexe**

### CODE REVIEW

**Comment by azawawi** [comment]
@ugexe It is still failing on macOS

**Comment by ugexe** [comment]
Your windows tests have been failing ever since you switched to github actions

**Comment by azawawi** [comment]
@ugexe  Will bump it and investigate the windows failure separately in 1.0.4

Two test failures in `t/04-simple.rakutest`.

**Comment by azawawi** [comment]
> Your windows tests have been failing ever since you switched to github actions

Opened https://github.com/azawawi/raku-file-which/issues/24. It is not related to github actions. I just tested it on my windows machine and it is also failing there.

**Pull request merged**
